-- apply changes
create table auth_identity (
  id                            uuid not null,
  constraint pk_auth_identity primary key (id)
);

create table auth_permission (
  id                            uuid not null,
  name                          varchar(255),
  constraint uq_auth_permission_name unique (name),
  constraint pk_auth_permission primary key (id)
);

create table auth_role (
  id                            uuid not null,
  name                          varchar(255) not null,
  constraint pk_auth_role primary key (id)
);

create table auth_token (
  token                         char(32) not null,
  authentication_id             uuid not null,
  last_used                     timestamptz,
  constraint uq_auth_token_authentication_id unique (authentication_id),
  constraint pk_auth_token primary key (token)
);

create table authentication (
  id                            uuid not null,
  identity_id                   uuid not null,
  constraint pk_authentication primary key (id)
);

create table didentity_role_bridge (
  identity_id                   uuid,
  role_id                       uuid,
  constraint uq_didentity_role_bridge_role_id unique (role_id)
);

create table drole_permission_bridge (
  role_id                       uuid not null,
  permission_id                 uuid not null,
  constraint uq_drole_permission_bridge_permission_id unique (permission_id)
);

create table duser (
  id                            uuid not null,
  minecraft_uuid                uuid,
  discord_id_discord_id         bigint,
  constraint uq_duser_minecraft_uuid unique (minecraft_uuid),
  constraint uq_duser_discord_id_discord_id unique (discord_id_discord_id),
  constraint pk_duser primary key (id)
);

create table user_basic_credentials (
  id                            uuid not null,
  user_id                       uuid not null,
  auth_identity_id              uuid not null,
  username                      varchar(255) not null,
  password                      varchar(255) not null,
  constraint uq_user_basic_credentials_user_id unique (user_id),
  constraint uq_user_basic_credentials_username unique (username),
  constraint uq_user_basic_credentials_auth_identity_id unique (auth_identity_id),
  constraint pk_user_basic_credentials primary key (id)
);

create table user_discord (
  discord_id                    bigint generated by default as identity not null,
  user_id                       uuid,
  constraint uq_user_discord_user_id unique (user_id),
  constraint pk_user_discord primary key (discord_id)
);

create table user_minecraft (
  uuid                          uuid not null,
  user_id                       uuid,
  constraint uq_user_minecraft_user_id unique (user_id),
  constraint pk_user_minecraft primary key (uuid)
);

-- foreign keys and indices
alter table auth_token add constraint fk_auth_token_authentication_id foreign key (authentication_id) references authentication (id) on delete restrict on update restrict;

create index ix_authentication_identity_id on authentication (identity_id);
alter table authentication add constraint fk_authentication_identity_id foreign key (identity_id) references auth_identity (id) on delete restrict on update restrict;

create index ix_didentity_role_bridge_identity_id on didentity_role_bridge (identity_id);
alter table didentity_role_bridge add constraint fk_didentity_role_bridge_identity_id foreign key (identity_id) references auth_identity (id) on delete restrict on update restrict;

alter table didentity_role_bridge add constraint fk_didentity_role_bridge_role_id foreign key (role_id) references auth_role (id) on delete restrict on update restrict;

create index ix_drole_permission_bridge_role_id on drole_permission_bridge (role_id);
alter table drole_permission_bridge add constraint fk_drole_permission_bridge_role_id foreign key (role_id) references auth_role (id) on delete restrict on update restrict;

alter table drole_permission_bridge add constraint fk_drole_permission_bridge_permission_id foreign key (permission_id) references auth_permission (id) on delete restrict on update restrict;

alter table duser add constraint fk_duser_minecraft_uuid foreign key (minecraft_uuid) references user_minecraft (uuid) on delete restrict on update restrict;

alter table duser add constraint fk_duser_discord_id_discord_id foreign key (discord_id_discord_id) references user_discord (discord_id) on delete restrict on update restrict;

alter table user_basic_credentials add constraint fk_user_basic_credentials_user_id foreign key (user_id) references duser (id) on delete restrict on update restrict;

alter table user_basic_credentials add constraint fk_user_basic_credentials_auth_identity_id foreign key (auth_identity_id) references auth_identity (id) on delete restrict on update restrict;

alter table user_discord add constraint fk_user_discord_user_id foreign key (user_id) references duser (id) on delete restrict on update restrict;

alter table user_minecraft add constraint fk_user_minecraft_user_id foreign key (user_id) references duser (id) on delete restrict on update restrict;

