ARG JAVA_VERSION
FROM ${JAVA_VERSION}

ARG JAR_FILE
ARG WORKINGDIR

WORKDIR ${WORKINGDIR}
COPY ./${JAR_FILE} /program/${JAR_FILE}

ENTRYPOINT cp /program/${JAR_FILE} ${WORKINGDIR}/${JAR_FILE} && \
java -jar ${WORKINGDIR}/${JAR_FILE}
