version: '3.8'
services:
    cloverbot:
        restart: unless-stopped
        container_name: ${COMPOSE_NAME}.${CLOVER_IMAGE}
        image: ${COMPOSE_NAME}/${CLOVER_IMAGE}
        build:
            context: .
            args:
                - GRADLE_VERSION=${GRADLE_VERSION}
                - JAVA_VERSION=${JAVA_VERSION}
                - WORKINGDIR=${WORKINGDIR}
        volumes:
            - '${MOUNT_DIR}:${WORKINGDIR}/data'
