version: '3.8'
services:
  api:
    depends_on:
      - postgres
    restart: unless-stopped
    container_name: ${COMPOSE_NAME}.${JAVA_IMAGE}
    image: ${COMPOSE_NAME}/${JAVA_IMAGE}
    build:
      context: .
      dockerfile: ./serve/api/Dockerfile
      args:
        - JAVA_VERSION=${JAVA_VERSION}
        - JAR_FILE=${JAR_FILE}
        - WORKINGDIR=${WORKINGDIR}
    environment:
      - JAR_FILE=${JAR_FILE}
      - WORKINGDIR=${WORKINGDIR}
    volumes:
      - '${MOUNT_DIR}/java:${WORKINGDIR}'
    networks:
      - 'wynncloud'
      - 'cloverbot'
  website:
    restart: unless-stopped
    container_name: ${COMPOSE_NAME}.${WEB_IMAGE}
    image: ${COMPOSE_NAME}/${WEB_IMAGE}
    build:
      context: .
      dockerfile: ./serve/website/Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    environment:
      - NGINX_PORT=${NGINX_PORT}
    networks:
      - 'wynncloud'
  postgres:
    restart: unless-stopped
    image: ${POSTGRES_VERSION}
    container_name: ${COMPOSE_NAME}.${DATABASE_IMAGE}
    environment:
      - POSTGRES_USER_FILE=/secrets/${POSTGRES_USER_FILE}
      - POSTGRES_PASSWORD_FILE=/secrets/${POSTGRES_PASSWORD_FILE}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - 'cloverbot'
    ports:
      - '5431:5432'
    volumes:
      - ${MOUNT_DIR}/database:/var/lib/postgresql/data
      - ${MOUNT_DIR}/secrets:/secrets
networks:
  cloverbot:
    name: 'cloverbot'
  wynncloud:
    name: 'wynncloud'
